### ISSUE TITLE
WSLg: Bépo keyboard layout switches to Qwerty in WSLg

### ISSUE THREAD

**Issue by Wolfy76700** [microsoft/wslg#1060]
### Windows build number:

Microsoft Windows NT 10.0.22621.0

### Your Distribution version:

20.04

### Your WSL versions:

```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1555
```

### Steps to reproduce:

1. Install the Bépo keyboard layout from [here](https://download.tuxfamily.org/dvorak/windows/1.1rc2/bepo-1.1rc2-full.exe) (Source: https://bepo.fr/wiki/Windows)
2. Reboot the computer
3. Set your keyboard to the French-Bépo layout
4. Open a WSLg application with textboxes

### Expected behavior:

Hitting the keyboard keys should enter matching characters (e.g. BÉPOÈ -> BÉPOÈ)

### Actual behavior:

Hitting the keyboard keys should enters characters using the Qwerty layout (e.g. BÉPOÈ -> QWERT)

**Comment by hideyukn88** [comment]
@Wolfy76700, thanks for reporting the issue, I believe basically this is the same issue as  https://github.com/microsoft/wslg/issues/696. Currently 3rd party keyboard layout is not supported by WSLg since 3rd party keyboard layout does not have keyboard layout ID uniformly assigned by Microsoft, thus in order to support such layout, it has to be treated as custom keyboard layout, which is tracked by https://github.com/microsoft/wslg/issues/173, thanks!
