### ISSUE TITLE
wslg.exe is missing after running wsl --update on Windows 10

### ISSUE THREAD

**Issue by tzengshinfu** [microsoft/wslg#1146]
### Windows build number:

10.0.19045.0

### Your Distribution version:

20.04

### Your WSL versions:

WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3031

### Steps to reproduce:

Run dos command `wsl --update` in Command Prompt window.

### Expected behavior:

Display Linux GUI app screen normally.

### Actual behavior:

`wslg.exe is not recognized as an internal or external command, operable program or batch file.`
Because wslg.exe is missing.

**Comment by mr1chter** [comment]
As noted in #1143 the `wslg.exe` binary probably has been moved (to `C:\Program Files\WSL\wslg.exe`). If you, like me, started your linux GUI apps via an automatically generated shortcut and then had this message, just check your start menu, in my case those have been generated anew and you might have to swap your old shortcut for a new one. 

But since you did not write how you opened your GUI app, I can only guess as well.

**Comment by tzengshinfu** [comment]
Hello, Mr1chter:

Thank you for your reply.
Earlier, I checked the system-generated Linux GUI shortcut and found that wslg.exe was indeed moved from "%USERPROFILE%\AppData\Local\Microsoft\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_xxxxxxxxxxxxx"
to
"C:\Program Files\WSL".

I will correct all the referenced paths.
![image_20231122_082234](https://github.com/microsoft/wslg/assets/2170033/85f7e0b1-0969-4982-95f2-f4b0b1a42f69)
