### ISSUE TITLE
Drawing error in GUI

### ISSUE THREAD

**Issue by YumeAyai** [microsoft/wslg#1149]
### Windows build number:

10.0.19045.3693

### Your Distribution version:

22.04

### Your WSL versions:

WSL 版本： 2.0.7.0
内核版本： 5.15.133.1-1
WSLg 版本： 1.0.59
MSRDC 版本： 1.2.4677
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.25880.1000-230602-1350.main
Windows 版本： 10.0.19045.3693

### Steps to reproduce:

![image](https://github.com/microsoft/wslg/assets/93071993/dd56f7af-5bd1-4029-8cd9-7888b02b353e)

### Actual behavior:

Some parts of the interface might not appear or display incorrectly.
Except words. Drawing error always occur near the words in GUI

**Comment by SJoJoK** [comment]
Same here.

**Comment by elandutra** [comment]
Same here.

Versão do WSL: 2.0.9.0
Versão do kernel: 5.15.133.1-1
Versão do WSLg: 1.0.59
Versão do MSRDC: 1.2.4677
Versão do Direct3D: 1.611.1-81528511
Versão do DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versão do Windows: 10.0.22631.2792
![image](https://github.com/microsoft/wslg/assets/56735820/d600303f-d319-489a-8ed3-2b36f95889a6)

**Comment by guokeme** [comment]
My wsl version information is as follows:
![image](https://github.com/microsoft/wslg/assets/12101271/b562e35b-8275-4a65-9e5d-b96e53364120)
After my repeated testing, I can determine the following:

When I use the `wsl -t Ubuntu-22.04` command to terminate my Ubuntu, and then restart the GUI program, a blurred screen will appear;
When I use the `wsl --shutdown` command to terminate my wsl, and then restart the GUI program, there will be no blurred screen;
So it can be speculated that this bug is caused by the wsl -t command, and this command may also be used when the Windows system is shut down, thus causing the bug. I hope this comment will be seen.

OK, I use the` wsl --update --pre-release` command to update wsl, the bug fixed.
