### ISSUE TITLE
No ps command in WSLg system distro

### ISSUE THREAD

**Issue by cerebrate** [microsoft/wslg#126]
**Is your feature request related to a problem? Please describe.**
When attempting to solve problems or indulging my curiosity as to what's going on in there, I want to see what's running under the covers. Without `ps`, it's inconveniently hard to find out!

**Describe the solution you'd like**
Please add `ps` to the system distro. `/proc`, `ls`, and `cat` together don't really cut it as a substitute!

**Comment by spronovo** [comment]
I totally agree :-)... we used to have this, but some aggressive trimming of the packages remove it... we'll add this back.

You can do the following to add it back... but you'll need to do it every time you launch the system since the system distro is read-only and any changes to it are not persistent.

```
tdnf install procps-ng
```

**Comment by spronovo** [comment]
We added this support in version 1.0.22 of WSLg which has been released earlier today. To update, please run the following from an elevated command prompt:

```
wsl --shutdown
wsl --update
```
