### ISSUE TITLE
Feature: WSLg support for Zed

### ISSUE THREAD

**Issue by tadghh** [microsoft/wslg#1271]
### Is your feature request related to a problem:

Not related to a probelem

### Describe the solution you'd like:

It opens a window containing Zed!

### Describe alternatives you've considered:

Did not find any documentation about using WSLg with custom application

### Additional context:

https://zed.dev/linux

**Comment by linghengqian** [comment]
- How does this relate to WSLg? Do you get any WSLg-specific errors when you run `curl https://zed.dev/install.sh | sh`?

**Comment by linghengqian** [comment]
From my perspective this is an issue on Zed's side, they don't provide documentation. This has nothing to do with WSLg.

**Comment by linghengqian** [comment]
> > From my perspective this is an issue on Zed's side, they don't provide documentation. This has nothing to do with WSLg.
> 
> How does WSLg work with gimp? I assumed it was a universal wrapper.

- WSLg is so easy to use with gimp that you only need to install gimp and then run `gimp`. Any application should maintain its own documentation for use on WSLg, rather than relying on a documentation page for Micrsoft WSL to provide an introduction.
- ![image](https://github.com/user-attachments/assets/6497554f-e921-4d26-a082-7005988aa07c)

**Comment by linghengqian** [comment]
I believe there is a misunderstanding here. There are so many software that can run on WSLg that you can completely assume that if a software can run on a normal Linux distribution, it must be able to run on WSLg in a similar installation method, which does not require any documentation on the WSLg side. If a software does not run under WSLg, the first thing to contact is the software developer rather than the operating system developer.

**Comment by linghengqian** [comment]
I tried to alleviate the issues on the zed side at https://github.com/zed-industries/zed/pull/47185 , but a better approach would be to merge https://github.com/microsoft/weston-mirror/pull/159 .
