### ISSUE TITLE
(EE) no screens found(EE)

### ISSUE THREAD

**Issue by pavelpc** [microsoft/wslg#180]
# Environment

```none
Windows build number:Microsoft Windows [Version 10.0.21376.1]
Your Distribution version:  Ubuntu Release: 20.04
Your WSLg version: 1/0/19
```

# Steps to reproduce
sudo startx
sudo su 
startx
#  Expected behavior
i want to start full gui
[pulseaudio.log](https://github.com/microsoft/wslg/files/6453154/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/6453164/weston.log)
root@pavelpc:/mnt/c/Users/pavel# echo $DISPLAY
:0
root@pavelpc:/mnt/c/Users/pavel# ls -la /tmp/.X11-unix
lrwxrwxrwx 1 pavelpc pavelpc 19 May 10 18:47 /tmp/.X11-unix -> /mnt/wslg/.X11-unix
root@pavelpc:/mnt/c/Users/pavel# ls /tmp/.X11-unix
X0
root@pavelpc:/mnt/c/Users/pavel# cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.19+Branch.main.Sha.2a47bf20c239b523d7413f315cbc9ee60dfde831
Mariner: VERSION="1.0.20210224"
FreeRDP: 5f083fa0b97d433d6204985f6047886e29c1c61e
weston: 16de531f00aa3dfd17e0de74c8f49e9fd7cec617
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
# Actual behavior
root@pavelpc:/mnt/c/Users/pavel# startx
_XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 22
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
X.Org X Server 1.20.8
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-177-generic x86_64 Ubuntu
Current Operating System: Linux pavelpc 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64
Kernel command line: initrd=\initrd.img panic=-1 nr_cpus=16 swiotlb=force pty.legacy_count=0
Build Date: 06 April 2020  09:39:29AM
xorg-server 2:1.20.8-2ubuntu2 (For technical support please see http://www.ubuntu.com/support)
Current version of pixman: 0.38.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Mon May 10 19:09:24 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIOPorts: failed to set IOPL for I/O (Function not implemented)
xf86EnableIOPorts: failed to set IOPL for I/O (Function not implemented)
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error

**Comment by spronovo** [comment]
Hello @pavelpc, what you are trying to do here is unfortunately not supported / possible. WSLg allows you to run individual X11 or Wayland client applications against our built-in server (which actually happen to be X.org through Xwayland), but you can run X.org directly as you are trying to do here. 

If you would like to run a different X server than the one provided by WSLg, you can look at alternative like X410 (https://x410.dev/) or Xming (https://xming.en.softonic.com/) or other great alternative.

**Comment by mick-p1982** [comment]
@spronovo Can you say if this is on the long term agenda for wslg? It seems reasonable to some Linux development tasks (work and troubleshooting) in a natural development environment for it like a Remove Desktop scenario. Wslg is built on RDP? Remote Desktop right?

**Comment by spronovo** [comment]
Hey @mick-p1982, there are currently no plan to redirect the Linux/Weston desktop as a whole back to Windows instead of individual applications. You need to keep in mind here that we are running Weston, not GNOME, KDE or some cool/advanced Linux desktop environment... Weston is a sample compositor, the Weston desktop Shell is very basic, not something a regular user would want to use. You actually can run an instance of Weston on top of WSLg if you want to try it... Weston has a Wayland backend that can redirect to a Wayland compositor... for example if you launch Weston with the command line ```weston --backend=wayland-backend.so --xwayland``` you'll have Weston run on top of WSLg (effectively Weston on top of Weston) and look something like below:

![image](https://user-images.githubusercontent.com/7545376/121122738-d2e3b800-c7d6-11eb-88b1-aeb4c2fa91ef.png)

We expect folks that want to run a full Linux desktop environment to either run Linux natively or to run it in a VM that they manage as opposed to WSLg.

Also if you want to launch a GUI application from the console without the console waiting on the GUI application to return, you can add ```&``` at the end of your command, for example the following will launch xclock from a console and the console will wait for xclock to return:

```xclock```

That's the default behavior... but if you don't want the console to wait on the GUI application to return you can type this instead:

```xclock &```

**Comment by mick-p1982** [comment]
This seems like a proper solution to this Issue. I set up a shortcut using this (https://github.com/Microsoft/WSL/issues/510#issuecomment-575792587) trick to start Weston/Wayland in this mode (put the starting directory to the `\\wsl.localhost\*` home directory.)

I wonder if this would work for a full Linux desktop like Gnome in some capacity? And are there any drawbacks? Is it the same in acceleration terms? Implementation aside a formal system would be nice to complement WSLg. A Windows Store instance could include a shortcut to start it in this mode. That seems reasonable after downloading a graphics enabled Ubuntu app. The packages could be downloaded on demand. My dependencies for weston/xwayland were only about 20MB combined, more unpacked.

[More off-topic: Forgive me, by VM do you mean inside WSL or by another means? As it happens I'm having trouble with VM with a fresh WSLg install on a fresh PC that's otherwise working. Maybe you can pass it (https://www.reddit.com/r/bashonubuntuonwindows/comments/nv1yge/nested_vm_need_network_connection_fix_of_som/) along to someone concerned about VM inside WSL? It seems like a regression because there are guides online from last year that seem to not had the same trouble.]
