### ISSUE TITLE
pkexec error

### ISSUE THREAD

**Issue by shajul** [microsoft/wslg#252]
`Error getting authority: Error initializing authority: Could not connect: No such file or directory`

This is for both pkexec and apps relying on pkexec like synaptic-pkexec

**Comment by fflorey** [comment]
Dear shajul, your report is not so easy to reproduce, as you don't give the needed information. Please take a look of the needed infos, if you report a bug.

I looked at it on my machine (Build: 21387.1), WSL2 running Ubuntu 20.04): 
I do get the same error. If you run strace, i see the line: 
`connect(5, {sa_family=AF_UNIX, sun_path="/var/run/dbus/system_bus_socket"}, 110) = -1 ENOENT (No such file or directory)`
For my understanding, dbus (D-BUS) is used by desktop systems like kde and others. As i dont have that installed on my machine, i assume the error comes from the missing environment.
You might try to install such a system, or try to install the needed dbus libs instead. 
Or just use su instead of pkexec(?)

I think this is nothing related to wslg... (but i am just a user, so i am guessing somehow)

**Comment by shajul** [comment]
The start menu shortcut is added for synaptic-pkexec, which does not work.. That is why I reported the bug.. 
dbus-x11 package does not solve it.. It is related to missing XAUTHORITY env variable

**Comment by enigma131** [comment]
Same thing detected here. Seams policy kit isn't installed. Have you solved the issue with a workaround ?
