### ISSUE TITLE
[Question] How to make mpv GPU accelerated?

### ISSUE THREAD

**Issue by PhyX-Meow** [microsoft/wslg#299]
I have installed wslg 1.0.12, mesa 21.1.2 with d3d12 support, Nvidia driver 470.76, but mpv is still using software rendering.
Windows version: 10.0.21390.2025
Distro: Manjaro linux testing

```
❯ mpv Ensemble\ for\ Polaris-rweQmBxc2lc.webm
 (+) Video --vid=1 (*) (vp9 1080x1080 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
NVD3D10: CPU cyclestats are disabled on client virtualization
NVD3D10: CPU cyclestats are disabled on client virtualization
[vo/gpu/opengl] Suspected software renderer or indirect context.
NVD3D10: CPU cyclestats are disabled on client virtualization
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu/vulkan/libplacebo] Found no suitable device, giving up.
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan device
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
[vo/gpu/vulkan/libplacebo] Found no suitable device, giving up.
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan device
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
AO: [pulse] 48000Hz stereo 2ch float
VO: [wlshm] 1080x1080 yuv420p
```

How can I make it use my GPU? Appreciate any help.

**Comment by onomatopellan** [comment]
There are two types of gpu acceleration for mpv:
* Video decoding acceleration (VDPAU, DXVA): Not available. For this Nvidia would need to implement it in a new Windows driver.
* OpenGL to D3D12 rendering acceleration: which is included with Mesa 21.x but only if the library `/usr/lib/x86_64-linux-gnu/dri/d3d12_dri.so` is present. Since you are seeing the message "NVD3D10: CPU cyclestats are disabled on client virtualization" mpv is already using this for the video rendering. It's still not fully accelerated but you should notice the GPU usage in task manager.

**Comment by PhyX-Meow** [comment]
Got it, closing this.
