### ISSUE TITLE
Invalid command line option

### ISSUE THREAD

**Issue by Bhavesh012** [microsoft/wslg#32]
I have an existing WSL2 installation of Ubuntu 20.04. On running `wsl --update` on  Administrator: Command Prompt, it gave this error:

```
Microsoft Windows [Version 10.0.19042.928]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>wsl --list -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Stopped         2

C:\WINDOWS\system32>wsl --update
Invalid command line option: --update
Copyright (c) Microsoft Corporation. All rights reserved.
```
## System Specifications

```
OS:              Windows 10
Distributor ID:  Ubuntu
Description:     Ubuntu 20.04.2 LTS
Release:         20.04
Codename:        focal
Python:          Python 3.8.8
pip:             21.0.1

$ uname -a: Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by JYInMyHeart** [comment]
Windows 10 build 19042 is not supported by wslg.

**Comment by Bhavesh012** [comment]
Ah, okay. My bad.

**Comment by the-dag** [comment]
> Windows 10 build 19042 is not supported by wslg.

I don't know what "wslg" is, but JYInMyHeart seems to feel this makes it perfectly natural that `wsl --install` should fail. Or maybe, since this is a "wslg" repo, this is the wrong place to complain about wsl --install failing? If so, I apologize for posting - but it's not easy to know everything about your projects and I have limited time on Earth like the rest of us.

According to https://docs.microsoft.com/en-us/windows/wsl/install#step-4---download-the-linux-kernel-update-package `wsl --install` is "the preferred way" to install a distro and should work on "Windows 10 version 2004 and higher (Build 19041 and higher)".

I thought 19042 was "higher" than 19041. My brand new laptop with Win10 Pro 19042.928 on it can't run Docker Desktop because of this. I basically cannot get any work done, and that is not the hoped-for effect on productivity when buying a new laptop. :(

-- The remainder is a rant, and a digression; you need not read this if you are sensitive to such things.

Some things never change. The Microsoft User Experience has always been crappy, and it still sucks balls. Sure, many things have improved, but overall it is still doing all the things users have hated for decades. and adding new stuff that also doesn't work. 

To give a little insight into why I speak such crass words, here is a short tale describing what it has been like for me getting a new laptop. I started out with installing Office. For this, I went to my company's Office365 portal and quickly found it. The installer worked flawlessly; great, now I can get back on Teams... except Teams was not installed. Ok, that's a minor gripe. Go find Teams, install it, and try to run it. Now a login dialog appears. It says to log on with my "Microsoft account". I use the credentials I use to log on to my company's domain, as this often seems to be considered a "Microsoft account". And it worked; wonderful. Now launch Outlook. It too asks for my Microsoft account. IDK why the same account I am already logged on to, my AD credentials, are necessary for each Office app (or indeed any at all; the OS knows who I am and it should be possible to get this working easily - ironically it kinda did when I configured Outlook on my iPad). But we use "app passwords" for Exchange, so I figured I had to use that. Looking around Office365 for a *long* time did not help, I cannot find the thing in there. Instead, I had to use the Outlook web client to search my mailbox and find instructions I received awhile back, and hope they still applied. Finally I got in there, generated a new app password, and attempted using it in the dialog presented by Outlook. 

That worked - for the rest of the day. Next morning, Outlook again prompts for my password. In the meantime, I've been through logging into "my Microsoft account" about a gazillion times. That dialog, btw, is confusing as heck! It says it can keep me logged in "across all devices" (but seems not to even manage to keep me logged in on a single device) but has a _separate_ checkbox that controls whether or not "my organization" administers my computer (which it de facto does anyway, but through some other mechanisms that this thing is not aware of). It has a _button_ to proceed and presumably have me logged inn "across apps" but a _linkbutton_ to "only login this app". Regardless if I tick the checkbox or not, using the button always results in a lot of waiting followed by "something went wrong". So I use the linkbutton instead, and have to repeat this for every app. But where it gets real fun is when I try to use the Microsoft store. It too wants to know about my Microsoft account - one wonders why this thing isn't centralized, in a way that just works, it should be a simple thing! - but this one, contrary to the identically-looking dialog I get from many other apps, says "that account does not exist" when I enter my company email, which all the apps worked with. Since I would like to move on with my life and not spend an inordinate amouont of time understanding what the difference between a Microsoft account and a Microsoft account might be, I tried to follow the encouraging "Create account!" (with exclamation mark) link provided when the GUI says my account is suddenly gone. But when I enter the same email there it says "that account already exists". So I tried to ninja it by starting over and providing my phone number instead of my email address. This is on store in my "Microsoft account" linked to my company-AD credentials, and I know it is correct because I can choose to get a one-time code on SMS in all the _other_ apps (we use 2FA) and that works. But rather incredibly, the dialog then says "that doesn't look like a valid number". 

But back to Outlook's shenanigans. After it worked ok for half a day, suddenly my Inbox started showing a lot of emails that are over 2 years old. I archive old mail and try to keep a clean inbox, but this seems to be too confusing for Outlook to handle correctly. Out of curiosity I went to the web interface and there my inbox looked correct. But someone in MS has decided that signatures should be a desktop-only feature, which is frankly the only reason I know of to use the desktop app at all! Anyway, I selected the entire "older" group and archived it anew. This caused the client to hang for half an hour, so I had to use the web interface in the mean time. 

The next morning, I began my day by firing up Outlook. It immediately asked for credentials. WTF?! Since app passwords aren't supposed to be known by anyone, I had not written anything down, so now I had to waste more time finding the incredibly well hidden "create app password" functionality all over again. After eventually locating it, I created a new password and tried to log on with Outlook. This is what I did the day before and what had worked, if only for a day. But now it said the credentials were invalid. Then I realized the dialog looked different - the one yesterday looked like the one browsers display if they receive an HTTP authentication challenge. This one looked more like the dialog to log on to your _Microsoft account_. So I tried my AD credentials, and voila... we had progress... and I got the aforementioned "auth challenge" dialog (a gray one not respecting the user's theme that only asks for username and password with no furher explanation whatsoever). Now I used the app password I generated, and lo and behold, Outlook managed to connect to Exchange.

Now I know what the apologists will say. These things would work if my company had set things up this and this way. It may well be true that the user experience would be much better if various things I know nothing about were different regarding our domain or AD or some other bit involved in these things. But this is part of the problem with Microsoft: they seem to think "technically possible" equals "good idea". In reality, leaving everything open and letting everyone change everything however they fancy just creates a ton of problems and security loopholes. At the very least the system needs to itself be able to figure out if something will work BEFORE it leads the user down a path that is actually guaranteed to end in "something went wrong". And there is simply no exucse for things like the same dialog instance claiming both that an account does not exist and that the same account already exists, or for not being able to correctly validate a Norwegian phone number. 

Worst of all however is Microsoft's _attitude_ to users. Millions of people have _hated_ features and behaviours in Windows for literally _decades_, but do they listen? Nope! I wish whoever is responsible for designing the spell-checking features got stuck in MY user experience with that! For years I have had to spend countless hours staring at documents _filled_ with squiggly red lines because the god-damn thing cannot be turned off, cannot detect the correct language, and even continues to insist everything should be correct English despite my input locale (and my keyboard layout, but that should NOT determine this) is set to Norwegian! In Word, in Outlook, in OneNote... I guesstimate having spent perhaps 50 extremely frustrating hours over the past 15 years attempting to get rid of this. In any case it is difficult to write about NuGet or MSDTC or MSMQ or anything technical whatsoever and get the spell checker to feel happy, even if you only ever use English. I've tried to turn it off in a ton of apps and I've tried to turn it off in the OS. Occasionally I've had partial success and been less bothered than before for a while, but rest assured all the problems will return as soon as I need a new device.

All of this now triggered because I installed Docker Desktop on my new machine, it crashes during startup, but manages to report "The WSL 2 Linux kernel is now installed using a separate MSI update package" and provide a link to https://aka.ms/wsl2kernel, which redirects to the "docs.microsoft" page I linked above, which says wsl --install works on 19041 *or higher*. How I wish somebody would help solve the problem (getting WSL up and running), even IF what that page says is simply wrong and wsl --install is NOT supposed to work on this version of Windoze.
