### ISSUE TITLE
gui for nedit doesn't work

### ISSUE THREAD

**Issue by gobbedy** [microsoft/wslg#364]
# Environment

```none
Windows build number: 10.0.22000.65
Your Distribution version: ubuntu 20.04
Your WSLg version: 1.0.24
```

# Steps to reproduce
Install ```nedit``` (```sudo apt-get install nedit```)
Run ```nedit```: ```nedit```

```nedit``` GUI app does not open, unless I manually open an X-server as before.

Note that ```gedit``` GUI *does* work as expected, so it does appear that my GUI apps work in general.

Please let me know if you need logs, though I suspect it will be trivial to reproduce on your end.

**Comment by mgateno** [comment]
Interesting that you say that you need to run an xserver in order to get the gui apps to work at all. In theory this should not be necessary. If so, we are having the same problem, I suspect caused because we both did it the other way before.

**Comment by onomatopellan** [comment]
For diagnosing non working WSLg take a look at [the wiki](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg)

Normally after using another xserver these should be enough to get WSLg working:
```
export DISPLAY=:0
sudo rm -r /tmp/.X11-unix
ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
```

**Comment by gobbedy** [comment]
@mgateno I do not need an xserver in order to get gui apps to work.

GUI apps work without an xserver. It's just nedit that only works when I manually start an xserver.

@onomatopellan my WSLg is fully working, as far as I know. Were you unable to reproduce with the steps I gave?

**Comment by onomatopellan** [comment]
@gobbedy I can reproduce it sometimes. After running `wsl.exe --shutdown` works again although this https://github.com/microsoft/wslg/issues/307 happens.

**Comment by mgateno** [comment]
> For diagnosing non working WSLg take a look at [the wiki](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg)
> 
> Normally after using another xserver these should be enough to get WSLg working:
> 
> ```
> export DISPLAY=:0
> sudo rm -r /tmp/.X11-unix
> ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
> ```

I was able to get mine to work using this list of commands. The problem was definitely with the X11 mappings. I have two remaining issues:

1. My Windows environment has mouse buttons swapped, but the linux apps do not obey this and I cannot find a way to configure this in WSL. 
2. Resizing the windows kills the app. As long as I run them as they popped up everything is OK. The minute I try to resize them all heck breaks loose. My computer has both an Intel and Nvidia (RTX2060) GPUs and I have installed the proper drivers for both of them as per the WSLg recommendations.

**Comment by hideyukn88** [comment]
Hi. thanks for reporting the issue.

@gobbedy, would you please clarify how do you run X server manually? WSLg should automatically start the X server (Xwayland) inside system-distro by monitoring X11 socket. On WSLg, "gedit" works as Wayland native app rather than X11 app. Thus I guess X server is not auto-starting in your case? How about other X11 app, such as Firefox, does it run without manually starting X server?

@mgateno, 
1: currently mouse button swap is not supported, which is reported at https://github.com/microsoft/wslg/issues/74.
2: crashing on resize is new to us, there is hang on resize is reported https://github.com/microsoft/wslg/issues/272. Do you see any core dumps at /mnt/wslg/dumps?

Currently currently we are aware of two outstanding issues with nedit, https://github.com/microsoft/wslg/issues/141 and https://github.com/microsoft/wslg/issues/307.

Thanks for trying out WSLg!

**Comment by gobbedy** [comment]
@onomatopellan @mgateno Thanks, those commands did indeed work!

Thanks all for your help. Closing as this is fixed for me.
