### ISSUE TITLE
Unable to start windows manager

### ISSUE THREAD

**Issue by xquangdang** [microsoft/wslg#47]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21364.1]
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.17.1
```

# Steps to reproduce
Start bspwm tiling windows manager in command line
`$bspwm`

#  Expected behavior
Start new bspwm session

# Actual behavior
Another window manager is already running.

**Comment by spronovo** [comment]
WSLg ships Weston with a built-in window manager that can't be replace, so you will not be able to replace it with bspwm.

**Comment by isubasinghe** [comment]
Is that accurate? I got Sway to sort of work 
Surely there isnt too many issues to get it fully working

**Comment by isubasinghe** [comment]
![image](https://user-images.githubusercontent.com/28187128/115883963-b93e1980-a491-11eb-829c-5124a88c7ab5.png)

**Comment by isubasinghe** [comment]
I'll mess around and see if I can get it working and update here

**Comment by mklllr** [comment]
@isubasinghe any updates?

**Comment by isubasinghe** [comment]
Unfortunately none, but imo it probably is at a stage where someone can get it working somehow with a lot of effort, unfortunately I dont have that kind of energy at the moment, I think I'm personally going to stick to my arch installation until this issue is sorted. 

I'm just way more productive with my current setup.

**Comment by fhill2** [comment]
@klllr @isubasinghe I'm experimenting with Xephyr + i3 atm. Xephyr starts a nested x server which appears as a client to the XWayland server. It's not a solution, definitely a workaround. I'm getting a little latency introduced because of the nesting. Apart from that, things appear to be working ok (only been using for a day though).

```
nohup Xephyr :1 -fullscreen
DISPLAY=:1
i3
```

**Comment by SystematicError** [comment]
Using the Xephyr approach seems to work pretty well, however mouse movement and clicks dont seem to be registering through this method (tested with awesomewm). Any workarounds for this?
