### ISSUE TITLE
Remove/Disable Start menu shortcuts

### ISSUE THREAD

**Issue by RyanHir** [microsoft/wslg#484]
**Is your feature request related to a problem? Please describe.**
WSLg adds options to the Start menu that cannot be hidden/disabled. Items like printer and IBus preferences appear if installing ROS desktop where all GUI applications are intended to be started from the command line.

**Describe the solution you'd like**
A option to disallow the creation of start menu shortcuts.

**Describe alternatives you've considered**
Deleting the distro's folder in the Start menu directory in appdata. But the icons will come back shortly afterwards.

**Additional context**
Some uses of GUI on Linux are reliant on the shell for some use cases and the cluttering of the Start menu can get unnecessary.

**Comment by hideyukn88** [comment]
@RyanHir, this is currently possible with below please refer https://github.com/microsoft/wslg/wiki/WSLg-Configuration-Options-for-Debugging. Please set it to 'false'. Thanks!

;start menu integration (Linux app in Windows start menu)
WESTON_RDP_DISABLE_APPLIST=true

**Comment by RyanHir** [comment]
That did the trick, thank you.

For anyone else who comes around, I created the file in Administrator mode and filled it with the following
```
[system-distro-env]
WESTON_RDP_DISABLE_APPLIST=false
```

**Comment by DAmNRelentless** [comment]
I am actually a fan of the automatic addition of the installed apps to the Windows shortcuts.
I am just wondering how to do it manually for apps which are not installed via `apt install`.
What if I want to add something like IntelliJ (installed on WSL) to my start menu, task bar or desktop on Windows?

**Comment by nonvegan** [comment]
Just ran into this problem in the latest version of wsl (running wslg 1.0.47, Store version). Apparently the _WESTON_RDP_DISABLE_APPLIST_ key was replaced with _WESTON_RDP_APPLIST_ (see [diff](https://github.com/microsoft/wslg/wiki/WSLg-Configuration-Options-for-Debugging/_compare/b35ac963ebe237ff14b68cff0c0974c271ea6a49#diff-b027d9acb18e7745ddb70875970b1779739c601563a0d56e5d308145a2cc036eR39)).

In order to disable the menu shortcuts being created every time wsl started, I had to create a `.wslgconfig` file  in the `C:\Users\<UserName>` folder with the following:
```
[system-distro-env]
WESTON_RDP_APPLIST=false
```

**Comment by hideyukn88** [comment]
@nonvegan, that is correct, thanks for following up!
