### ISSUE TITLE
The letter 'd' keeps repeating when starting apps

### ISSUE THREAD

**Issue by Ueland** [microsoft/wslg#515]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.22000.258]
Your Distribution version:  Ubuntu 20.04
Your WSLg version: 1.0.26
```

# Steps to reproduce

**WSL logs**: 
[pulseaudio.log](https://github.com/microsoft/wslg/files/7357240/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/7357241/weston.log)

#  Expected behavior

Commands running without the letter 'd' getting repeated until i stop it

# Actual behavior

When running  commands like these, the letter 'd' keeps getting typed until i start typing myself. 

`wsl.exe --user <my-username> /home/<path-to-intelliJ>/bin/idea.sh`
`wsl.exe --user <my-username> konsole`

IntelliJ:
![intellij](https://user-images.githubusercontent.com/97825/137580849-b416e123-dad9-4d2c-ad86-04f5f4ae30c8.png)

konsole:
![konsole](https://user-images.githubusercontent.com/97825/137580855-79a4be7a-b55c-4fea-ae91-3eadcb02621c.png)

But, it does *not* happen if i execute a non-gui app like Bash in the same manner. It only triggers in the  "WSLg-world".

**Comment by nopain2110** [comment]
I've same problem with rubymine, but with 'w' character instead of 'd'

**Comment by jagd** [comment]
Updated today to windows 11 for WSLg, got the same issue after playing with `xterm` and `gvim`

> I've same problem with rubymine, but with 'w' character instead of 'd'

@nopain2110  Perhaps you have closed any tab/window with `ctrl+w`?


# To Reproduce

After `wsl --shutdown`  open `xterm`  in WSL
- If the `xterm` window is closed by mouse, there is no problem
- If the `xterm` window is closed by typing `Ctrl+d`,  then all window newly opened will not get rid of `Ctrl` or `d` (or both) until the user press any key.  It causes this `ddddddddddd` effect.

The same happens to `gvim`, when quit with `:q` instead of mouse click, similar effects appear.
