### ISSUE TITLE
CUDA GUI Apps Running Under Ubuntu 20.04 on WSLg not working

### ISSUE THREAD

**Issue by mw7301** [microsoft/wslg#566]
# Environment

```none
Windows build number: 22499
Your Distribution version: Ubuntu 20.04
Your WSLg version: version 2,  kernel version 5.10.60.1
```

# Steps to reproduce

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `pulseaudio.log`
* `weston.log`
* `versions.txt
[versions.txt](https://github.com/microsoft/wslg/files/7524453/versions.txt)
[pulseaudio.log](https://github.com/microsoft/wslg/files/7524454/pulseaudio.log)

`
[New Text Document.txt](https://github.com/microsoft/wslg/files/7524457/New.Text.Document.txt)
[weston.log](https://github.com/microsoft/wslg/files/7524449/weston.log)

#  Expected behavior
The expected behavior is for the GUI CUDA apps running under Ubuntu 20.04 under WSLg would be for them to display their graphics windows just like they do under Ubuntu running on a standalone computer.

# Actual behavior
When you install the CUDA Toolkit for WSL2 you get a bunch of example CUDA programs with their source code. Most of the text based CUDA applications work fine BUT when you run any of the GUI CUDA examples such as Mandelbrot, simpleTexture3D, volumeRender, particles, oceanFFT etc. or basically any of the GUI apps from their Graphics, Imaging or Simulation directories you will basically get the same program errors and then a segmentation fault.

**Comment by spronovo** [comment]
Hello @mw7301. This is because CUDA GUI application require the NVIDIA native GL driver which exposes extension for CUDA. OpenGL is accelerated in WSLg through Mesa mapping on top of our vGPU/DX12 projection and Mesa doesn't support those CUDA extension. To support this would require NVIDIA to bring their native GL driver to WSL. This is something probably best requested/discussed on the NVIDIA [forum](https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-on-windows-subsystem-for-linux/303) for WSL.

**Comment by mw7301** [comment]
Hey Steve,

Thanks for the explanation and I have already pursued this with Nvidia.

**Comment by mw7301** [comment]
Hi Steve,

I was wondering if you ever heard anymore about this from Nvidia? I mentioned this several on their WSL forum but I never heard anything.
