### ISSUE TITLE
Do Windows developers read these issues?

### ISSUE THREAD

**Issue by worldofgeese** [microsoft/wslg#610]
I'm seeing at least a hundred issues with zero response from WSLg developers. Should we be expecting anything from ticket submission? My [own ticket](https://github.com/microsoft/wslg/issues/600) has gone unaddressed by Microsoft developers together with every single ticket created since: no request for more information or any other kind of acknowledgment.

**Comment by dpeterc** [comment]
I am also surprised by the slow pace of development.
Wslg took a lot of effort to create, it is 90% there, but in its current state, it is not useful, it is more like a technology demo.
It is now 5 months since the last public release, and 7 months since some [critical bugs were reported](https://github.com/microsoft/wslg/issues/141).
I was certain that with its resources and advanced development process, Microsoft would iron out these problems by the end of this year, but I was wrong.

**Comment by dyharlan** [comment]
It really is a bummer considering the potential of WSLg. It's weird seeing regressions like apps having difficulty querying screen size or non-existent snapping happen in WSLg whereas other X Servers integrate much better in the desktop. I kinda wish though that they worked on the basics first before being ambitious with GL Rendering and other crazy shenanigans.

**Comment by hideyukn88** [comment]
@worldofgeese, sorry for late response, I post a comment on that topic, please take a look. Thanks!
