### ISSUE TITLE
Linux GUI apps look pixelated at Hi-DPi environment

### ISSUE THREAD

**Issue by XuCpeng** [microsoft/wslg#75]
# Environment

```none
Windows build number: 10.0.21364.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.17.1
Display Resolution: 3840*2160
```

# Steps to reproduce

Set display `Scale and layout` option to 175%,  and set `WESTON_RDP_DISABLE_FRACTIONAL_HI_DPI_SCALING=false`  in `.wslgconfig`.

1. Install `Intel GPU driver for WSL`
2. Install `ubuntu` from Microsoft Store
3. `sudo apt install firefox`
4.  open firefox

#  Expected behavior

Applications should be scaled and kept clear.

# Actual behavior

 Applications is scaled but blurred (or pixelated? ).  (Not only firefox, but also other applications have the same display effect.)

![image](https://user-images.githubusercontent.com/19551139/115950557-8b4aea80-a50e-11eb-8883-4b94a24b83cd.png)

I tried to reinstall WSL and Ubuntu, and tried to use 200% scaling, but it didn't work. I'm not sure if this is a bug or an unimplemented feature.

**Comment by hideyukn88** [comment]
@XuCpeng , thank you for reporting this, yes, this is currently known limitation due to the quality of scaling used in RDP client software in Windows OS (mstsc.exe). This is also tracked in https://github.com/microsoft/wslg/issues/3. 

Also if you prefer to let firefox to natively scale up, you can disable WSLg's auto scaling using the method mentioned at https://github.com/microsoft/wslg/issues/30, and enable HI-DPI scaling at firefox itself.

**Comment by spronovo** [comment]
This issue is already tracked by #3, closing as duplicate.

**Comment by Yogu** [comment]
> Also if you prefer to let firefox to natively scale up, you can disable WSLg's auto scaling using the method mentioned at #30, and enable HI-DPI scaling at firefox itself.

How do you enable Hi-DPI scaling in firefox (or any application that supports it?) On a native Linux environment (with KDE / Gnome), this usually just works out of the box and applications scale themselves properly and nicely. Don't really understand what the RDP client needs to do here. Is it possible to enable scaling (and also fractional scaling) for all applications that natively support it?

**Comment by hideyukn88** [comment]
@Yogu , there is no common framework for HI-DPI, so needs to be done by each framework or by applications separately, please refer https://wiki.archlinux.org/title/HiDPI, while this is for archlinux's wiki but apply to most of distro.

And the reason this is nicely done with, for example, Ubuntu desktop (from Canonical), is because, currently almost all Linux distro for WSL is mainly configured for console usage (not GUI), thus many of desktop specific packages/configurations are not installed/pre-configured by distro vendor. Thus those have to be done manually, this is similar to the situation when enabling GUI top on more console based distro, such as Ubuntu server.

**Comment by Yogu** [comment]
@hideyukn88 Ah, makes sense. Thanks!
