### ISSUE TITLE
gui issues

### ISSUE THREAD

**Issue by numeric-lee** [microsoft/wslg#792]
### Version

Version 10.0.19043.1806

### WSL Version

- [ x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

18.04

### Other Software

XLaunch                                      

### Repro Steps

the GUI fails to connect when I launch either chromium_browser or dbeaver                          

### Expected Behavior

display open

### Actual Behavior

display wouldn't open

### Diagnostic Logs

Have used WSL1 and WSL2 with GUI successfully for 3 years
it worked until a few days ago.

Someone edited my resolv.conf file recently (and possibly also wsl.conf) which may have caused the problem by installing resolvconf without success. I also tried an xrdp gui connection

**Comment by numeric-lee** [comment]
Thanks @elsaco  @benhillis and adding @spronovo    I commented out the this line  ` export DISPLAY="$(awk '/nameserver/ { print $2 }' < /etc/resolv.conf)":0` . I am at location 2 and I restarted terminal but I still get the same basic error

Unable to invit server: could not connect. Connection refused.
2022-07-20 17:09:42.077 - Create display                                                                                                      Unable to init server: Could not connect: Connection refused  

i see this thread  https://github.com/microsoft/wslg/issues/522 which doesnt shed much light. but  anticipating requests for additional information 
ls -la - tmp produces
![image](https://user-images.githubusercontent.com/60020188/180084624-ebef7364-a017-4163-a5ff-2b3d57b96649.png)

THis is frustrating especially because it worked well for three years. If I cant make it work my boss will probably :) make me switch to a MacBook

**Comment by numeric-lee** [comment]
As a parenthetical if I were (out of despair) to restore WSL2 would it help and could I avoid losing all the work in my wsl directory. Also, much as dislike switching to WIN11 (because o/s is too privacy invasive) , my machine could support it. Would there be a strong benefit from WSL GUI perspective to do so,  and how disruptive would it be

**Comment by elsaco** [comment]
@numeric-lee there's no need to move to Win11. `xvcsrv` on Win10 works very well with Linux GUI apps. The issue seems to be your `$DISPLAY` setting.

Before scripting it I'd do a manual setup to get it working, like:
 start `xvcsrv` w/out access control,  add `mcookie` later if you want access control
set `$DISPLAY` value to the IP of the gateway, which is also the IP of the `hns-endpoint` on the host
start `xterm` or another app to test your setup
if everything works script the `$DISPLAY` setting, since WSL changes IPs on each reboot


On Windows side check what's listening on TCP port 6000, the default X port. You might need to open  your firewall to allow TCP/6000 traffic.

Sample output:
```
PS C:\temp> Get-NetTCPConnection -LocalPort 6000

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting OwningProce
                                                                                                                        ss
------------                        --------- -------------                       ---------- -----       -------------- -----------
::                                  6000      ::                                  0          Listen                     6860
172.24.16.1                         6000      172.24.20.208                       53156      Established Internet       6860
127.0.0.1                           6000      127.0.0.1                           54224      Established Internet       6860
127.0.0.1                           6000      127.0.0.1                           54225      Established Internet       6860
127.0.0.1                           6000      127.0.0.1                           54223      Established Internet       6860
0.0.0.0                             6000      0.0.0.0                             0          Listen                     6860

```

On my system, `172.24.16.1` is the WSL gateway and `172.24.20.208` is a WSL client running `xterm` using `xvcsrv` for display.

If you want to keep your `/etc/resolv.conf` to a custom DNS, i.e. 8.8.8.8, that's fine, it won't interfere with `X` server. If you run `get-hnsendpoint` on Windows you'll notice that IP provides `GatewayAddress` and `DNSServerList` with the `IPAddress` being assigned to `eth0` inside WSL clients:

```
PS C:\temp> get-hnsendpoint


ID                 : 0650d094-b1c2-4572-8a12-d56bb7f08748
Name               : Ethernet
Version            : 47244640267
AdditionalParams   : @{SwitchId=5F84F136-A333-4B7A-BE3D-98ABA4074AAE; SwitchPortId=AAA490DB-04E2-4D9D-98FF-172F3DA7C07A}
Resources          : @{AdditionalParams=; AllocationOrder=2; Allocators=System.Object[]; CompartmentOperationTime=0; Flags=0;
                     Health=; ID=B41B35F9-0E35-4944-BA2A-A8AFA36D8AEE; PortOperationTime=0; State=1; SwitchOperationTime=0;
                     VfpOperationTime=0; parentId=ACB8D82A-5DD2-4D1F-AC13-7E2E07D099A1}
State              : 2
VirtualNetwork     : b95d0c5e-57d4-412b-b571-18a81a16e005
VirtualNetworkName : WSL
MacAddress         : 00-15-5D-AE-FB-67
IPAddress          : 172.24.20.208
PrefixLength       : 20
GatewayAddress     : 172.24.16.1
IPSubnetId         : e3fa5fd1-3c0f-49f9-ac4e-6e2a1d42c1d5
DNSServerList      : 172.24.16.1
SharedContainers   : {}
VirtualMachine     : 1F38C580-890F-4822-8305-D53E682C8E48
```

After everything works to your liking add this to your `.bashrc`:

`export DISPLAY=$(ip route | awk 'NR==1{print $3}'):0`

What this does is setting `$DISPLAY=a.b.c.d:0` by using the gateway IP address, and display `0`.

**Comment by numeric-lee** [comment]
@elsaco Thank you for your clear and helpful response.

I got it to work along the lines of what you suggested

in my case, (as a remote worker using a network ) neither Get-NetTCPConnection -LocalPort 6000 nor get-hnsendpoint provided any useful information. what DID work was ipconfig and I noticed the IPv4 Address at my location had changed slightly.   Once I updated the address in bashrc accordingly, it worked.

Your conviction that the problem was simply a bad DISPLAY setting was very helpful.   

Thank you again  ⭐⭐
