### ISSUE TITLE
Weston and FreeRDP mirror not available?

### ISSUE THREAD

**Issue by shyim** [microsoft/wslg#83]
The links in latest release are not working
https://github.com/microsoft/weston-mirror/commit/fd961f5cd116c9358d82ce94d139c1578e21bd00
https://github.com/microsoft/FreeRDP-mirror/commit/e4a2fc2053bd8c5f99455fcd08ffee7e5591567a

**Comment by viniciusjarina** [comment]
Hi @shyim thank you for the heads up.

The `1.0.17` was released without the history squashed, this is why the hashes are different. (Because we squashed the history before publish the repo)

If you are trying to build locally you can use these commits:
https://github.com/microsoft/FreeRDP-mirror/commit/f129b6be4c208233794f02b9a85a993347c1c13b
https://github.com/microsoft/weston-mirror/commit/f590a956c378eb2ab765d05cb2331386f19f8704


But 

Next release the hashes will match the repos.
