### ISSUE TITLE
systemd prevents opening GUI

### ISSUE THREAD

**Issue by OfekShilon** [microsoft/wslg#917]
### Windows build number:

22623.0

### Your Distribution version:

20.04

### Your WSL versions:

WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22623.1028

### Steps to reproduce:

1. Enable systemd in wsl.conf,
2. Install gedit (sudo apt install gedit)
3. wsl shutdown, start a new wsl session in terminal
4. run `gedit`.

Note that without systemd enabled, gui apps work fine.

### WSL logs:

[pulseaudio.log](https://github.com/microsoft/wslg/files/10178182/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/10178185/weston.log)

### Expected behavior:

gedit window.

### Actual behavior:

Programs seem to be running but no GUI is visible.

**Comment by OfekShilon** [comment]
Additional notes: 
(1) I started being affected by this only after updating wsl to the latest version
(2) Another user reported it in the last week in the comments on #90 , but that issue was closed so comments seem to be ignored.

I believe this should be high priority - the latest WSL is pretty much unusable now.

**Comment by hideyukn88** [comment]
@OfekShilon, thanks for reporting the issue, we think we understood the issue and about to release the fix in WSL 1.0.3 or newer, https://github.com/microsoft/WSL/releases/tag/1.0.3, thanks!

**Comment by hideyukn88** [comment]
@OfekShilon, sorry, I missed you are on 1.0.3 already, would you please share /mnt/wslg/stderr.log? thanks!

**Comment by OfekShilon** [comment]
[stderr.log](https://github.com/microsoft/wslg/files/10183012/stderr.log)

Thanks for the prompt reply!

**Comment by OfekShilon** [comment]
Is there a way to make `wsl --update` skip pre-releases?

**Comment by OneBlue** [comment]
> Is there a way to make `wsl --update` skip pre-releases?

wsl --update skips pre-releases by default (1.0.3 isn't a pre-release anymore which is probably why you got the update).

@hideyukn88: Looking at `stderr.logs`, I see:

```
dbus[44]: Unknown username "systemd-oom" in message bus configuration file
dbus[44]: Unknown username "pulse" in message bus configuration file
[...]
[21:46:21.542] <5>WSLGd: Run:104: pid 45 exited with status 0, /usr/bin/sh -c /usr/bin/dbus-launch /usr/bin/pulseaudio --log-target=file:/mnt/wslg/pulseaudio.log --load="module-rdp-sink sink_name=RDPSink" --load="module-rdp-source source_name=RDPSource" --load="module-native-protocol-unix socket=/mnt/wslg/PulseServer auth-anonymous=true" 
```

**Comment by OfekShilon** [comment]
@hideyukn88 @OneBlue  Anything found? Any more info I can provide?

**Comment by OneBlue** [comment]
@OfekShilon: I just noticed this in the pulse audio logs: 

```
E: [pulseaudio] socket-server.c: bind(): Address already in use
```

Do you have any other pulse audio running ? Maybe a systemd unit ? 

What's the output of: `sudo ss -l -p -x`  ?

**Comment by c4artisan** [comment]
i've been having this problem for a while now and for whatever reason can't seem to get it fixed no matter what i do
it started happening out of nowhere and stuff
anything i can do?

**Comment by mbaudier** [comment]
I am also having this issue (using the provided Debian distribution, upgraded to testing/bookworm/debian12)  :
- if systemd is not enabled, gedit and xeyes work properly and are displayed
- if systemd is enabled neither gedit not xeyes are working (they start and stay up, but nothing is displayed)

Note: xeyes is a simplistic application from the x11-apps package, which allows to test the display and the mouse.

When testing only with xeyes (in order to put aside all GTK/dbus etc. issues which could happen with gedit), I get the following error in /mnt/wslg/stderr.log :

/mnt/c/Users/mbaud/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe: line 1: MZ: command not found                                [08:54:05.532] <5>WSLGd: Run:104: pid 180 exited with status 127, /mnt/c/Users/mbaud/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe /v:21E9F4B1-D5D4-4FB3-92EF-36E4CD1E97CC /hvsocketserviceid:34F6A392-FACB-11E6-BD58-64006A7986D3 /silent /wslg /plugin:WSLDVC_PACKAGE /wslgsharedmemorypath:WSL\21E9F4B1-D5D4-4FB3-92EF-36E4CD1E97CC\wslg C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe\wslg.rdp

Somehow, this msrdc.exe seems to be missing. (It is the remote desktop client, right?)

More details about my setup below, but I am happy to test with other distributions if it is more efficient for you:

# uname -a
Linux LAPTOP-XXXXXX 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 GNU/Linux

# cat /etc/debian_version                                                                                                                               
bookworm/sid

> wsl --version
WSL version: 1.0.3.0                                                                                                                                                                         
Kernel version: 5.15.79.1                                                                                                                                                                    
WSLg version: 1.0.47                                                                                                                                                                         
MSRDC version: 1.2.3575                                                                                                                                                                      
Direct3D version: 1.606.4                                                                                                                                                                    
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2364

**Comment by OfekShilon** [comment]
@OneBlue:
> 
> ```
> E: [pulseaudio] socket-server.c: bind(): Address already in use
> ```
> 
> Do you have any other pulse audio running ? Maybe a systemd unit ?
> 
> What's the output of: `sudo ss -l -p -x` ?

This is the relevant snippet of what I get with systemd:
```
ofek@ofek-lap:~$ sudo ss -l -p -x | grep audio
u_str LISTEN  0       5                       /run/user/1000/pulse/native 30985                                            * 0                                   users:(("pulseaudio",pid=871,fd=3),("systemd",pid=848,fd=31))
u_dgr UNCONN  0       0                                                 * 37966                                            * 0                                   users:(("pulseaudio",pid=871,fd=5))
```

with systemd disabled, the same command returns empty.

**Comment by OneBlue** [comment]
@OfekShilon: Makes sense, looks like systemd starts another instance of pulseaudio on your machine.

The following commands should disable it (restart the distro with wsl.exe --shutdown to validate the fix):

```
systemctl --user stop pulseaudio.socket
systemctl --user stop pulseaudio.service
systemctl --user disable pulseaudio.socket
systemctl --user disable pulseaudio.service
systemctl --user mask pulseaudio.socket
systemctl --user mask pulseaudio.service
```

If that doesn't work, there's probably a systemd-wide unit running. You should be able to identify it via: `sudo systemctl -t service`

**Comment by OfekShilon** [comment]
> The following commands should disable it (restart the distro with wsl.exe --shutdown to validate the fix):
> 
This did disable pulseaudio (I see none in `sudo ss -l -p -x`), but gedit still fails to open. (after 2 --shutdown's)

> If that doesn't work, there's probably a systemd-wide unit running. You should be able to identify it via: `sudo systemctl -t service`

I couldn't see anything relevant.  `sudo systemctl -t service | grep pulse` and `sudo systemctl -t service | grep audio` return empty.
I attach fresh versions of the logs. (stderr renamed to stderr1, github is having trouble uploading it in its original name)

[weston.log](https://github.com/microsoft/wslg/files/10246168/weston.log)
[wlog.log](https://github.com/microsoft/wslg/files/10246170/wlog.log)
[stderr1.log](https://github.com/microsoft/wslg/files/10246176/stderr1.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/10246174/pulseaudio.log)

Note I didn't modify anything in the shipped wsl or systemd - just enabled it in wsl.conf.

**Comment by OfekShilon** [comment]
BTW if it would be helpful I'd be happy to coordinate a remote (even debugging) session on my machine - it has no sensitive info. 
I suspect this issue appeared in the latest wsl update and is about to affect many people.

**Comment by hagronnestad** [comment]
I can confirm that I have the same issue. GUI apps works when `systemd` is `disabled` only.

Distribution:
`Kali Linux`

WSL Versions:
```
>wsl -v
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.963
```

Snippet from `/mnt/wslg/stderr.log`:
```
[03:59:38.167] <5>WSLGd: Run:104: pid 23488 exited with status 127, /mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe /v:F01242EB-2588-449F-982B-15376DB01520 /hvsocketserviceid:8B31892B-FACB-11E6-BD58-64006A7986D3 /silent /wslg /plugin:WSLDVC_PACKAGE /wslgsharedmemorypath:WSL\F01242EB-2588-449F-982B-15376DB01520\wslg C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe\wslg.rdp
/mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe: line 1: MZ: command not found
[03:59:38.179] <5>WSLGd: Run:104: pid 23490 exited with status 127, /mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe /v:F01242EB-2588-449F-982B-15376DB01520 /hvsocketserviceid:8B31892B-FACB-11E6-BD58-64006A7986D3 /silent /wslg /plugin:WSLDVC_PACKAGE /wslgsharedmemorypath:WSL\F01242EB-2588-449F-982B-15376DB01520\wslg C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe\wslg.rdp
/mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe: line 1: MZ: command not found
[03:59:38.190] <5>WSLGd: Run:104: pid 23492 exited with status 127, /mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe /v:F01242EB-2588-449F-982B-15376DB01520 /hvsocketserviceid:8B31892B-FACB-11E6-BD58-64006A7986D3 /silent /wslg /plugin:WSLDVC_PACKAGE /wslgsharedmemorypath:WSL\F01242EB-2588-449F-982B-15376DB01520\wslg C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe\wslg.rdp
/mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe: line 1: MZ: command not found
[03:59:38.202] <5>WSLGd: Run:104: pid 23494 exited with status 127, /mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe /v:F01242EB-2588-449F-982B-15376DB01520 /hvsocketserviceid:8B31892B-FACB-11E6-BD58-64006A7986D3 /silent /wslg /plugin:WSLDVC_PACKAGE /wslgsharedmemorypath:WSL\F01242EB-2588-449F-982B-15376DB01520\wslg C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe\wslg.rdp
```

As you can see from the timestamps, I get massive amounts of these messages.

```
$ wc -l /mnt/wslg/stderr.log
198323 /mnt/wslg/stderr.log
```

The file in the log is actually just a two byte file containing `MZ`, which explains the error message:

```
$ cat /mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.Window
sSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe
MZ
```

If I try to locate the "real" (?) `msrdc.exe`, I find it here: `C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe`, which is not the same directory as the one referenced in the logs.

```
$ ls -alh /mnt/c/Program\ Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe/msrdc.exe
-r-xr-xr-x 1 hag hag 2.5M Dec 18 03:30 '/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe/msrdc.exe'
```

Is it trying to use `msrdc,exe` from the wrong Windows App-package?

**Comment by mbaudier** [comment]
The problem is now solved for me (I can have systemd + UI apps), by uninstalling and reinstalling all Linux-related Apps.

Form Windows Settings > Apps :
- uninstall the Debian App
- uninstall Windows Subsystem for Linux Update
- uninstall Windows Subsystem for Linux App

Please note that I did NOT uninstall WSL as an optional Windows component (requiring restart etc.).

Then I checked that I had the old wsl (wsl --version fails).
And I ran from a PowerShell terminal:
```
wsl --update
wsl --version (do not fail)
wsl --install Debian
```

In my previous tests I had installed WSL and Debian from the Microsoft Store, in order to test how it feels for a normal user. But it doesn't seem to make a difference for the end state: both Apps are now visible again in the Microsoft Store, as if I had installed them from the Store.

Then I started Debian (stable/bullseye/11) and installed the 'x11-apps' package. The test program 'xeyes' was starting properly and was visible.

Finally, I configure the activation of systemd in /etc/wsl.conf, and restarted WSL.
xeyes is still starting and visible, and systemd is available:
```
$ sudo systemctl status
...
State: running
```

I had been testing WSL for a few months already, before the transition to the Microsoft Store. So, I suspect something must have been wrong in my upgrade path, and that it is safer to uninstall/reinstall everything, and explicitly go through 'wsl --update'.

@hagronnestad Since you have exactly the same issue I had, maybe you could try to uninstall/reinstall everything as well?

**Comment by hagronnestad** [comment]
@mbaudier I've previously updated my WSL2 install to the Windows Store one as well, but last night I uninstalled all old packages and turned off the Windows feature as well. Then I reinstalled directly with `wsl --install`, but I still experience the issue. I did *NOT* remove my Kali install though.

**Comment by hideyukn88** [comment]
@hagronnestad, based on the provided log, your issue looks same as https://github.com/microsoft/WSL/issues/9257#issuecomment-1345550170, which is caused by failing to startup msrdc.exe. Have you installed any binfmt for Windows's executable format, such as mono? If that's the case, this is fixed by  https://github.com/microsoft/wslg/pull/926, and will be included in next WSL update, thanks!

**Comment by benken-parasoft** [comment]
In my case, the /mnt/wslg/stderr.log was growing indefinitely with a repeating error about "msrdc.exe exited" and "No such file or directory @../ProcessMonitor.cpp:72 (LaunchProcess)".  I worked around this by uninstalling "mono-runtime" which I wasn't using anyway.  I had just commented on this in issue 9257.

**Comment by hagronnestad** [comment]
@hideyukn88 I'm not convinced that I have the same issue, The messages in my `/mnt/wslg/stderr.log` is different. The file referenced exists, but seems corrupted. The file is 2 bytes only and contains `MZ`.

I've also removed mono as proposed in #9257, on both Kali and Ubuntu, but I still can't open GUI-apps when `systemd=true`.

**Comment by hideyukn88** [comment]
@hagronnestad, thanks for info. Would you please check the file from Windows' side by doing below? Do you see 2 bytes msrdc.exe as well? (mine shows newer pre-release version with newer msrdc.exe, so file size may differ from public release version). If you do see 2 bytes file from Windows side as well, does uninstalling and reinstalling WSL fix it? thanks!

```
C:\Program Files>dir msrdc.exe /S
 Volume in drive C is Local Disk
 Volume Serial Number is 8A57-EA51

 Directory of C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.4.0_x64__8wekyb3d8bbwe

12/14/2022  06:37 PM         2,568,096 msrdc.exe
               1 File(s)      2,568,096 bytes
```

**Comment by hideyukn88** [comment]
@hagronnestad, actually at your previous comment, https://github.com/microsoft/wslg/issues/917#issuecomment-1356642677, it shows you have 2.5M bytes file of msrdc.exe, where do you see 2 bytes file? thanks!

>> -r-xr-xr-x 1 hag hag **2.5M** Dec 18 03:30 '/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe/msrdc.exe'

**Comment by hagronnestad** [comment]
@hideyukn88, the 2.5Mb file is not the one referenced in the log.

From the log:
`[03:59:38.167] <5>WSLGd: Run:104: pid 23488 exited with status 127, /mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe /v:F01242EB-2588-449F-982B-15376DB01520 /hvsocketserviceid:8B31892B-FACB-11E6-BD58-64006A7986D3 /silent /wslg /plugin:WSLDVC_PACKAGE /wslgsharedmemorypath:WSL\F01242EB-2588-449F-982B-15376DB01520\wslg C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe\wslg.rdp
/mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe: line 1: MZ: command not found`

File from log: `/mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe`

From https://github.com/microsoft/wslg/issues/917#issuecomment-1356642677:
> The file in the log is actually just a two byte file containing MZ, which explains the error message:
> 
> ```
> $ cat /mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe
> MZ
> ```

`ls -al` also confirms that the file is just 2 bytes:

```
$ ls -al /mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe
-r-xr-xr-x 1 hag hag 2 Dec 18 03:30 /mnt/c/Users/heina/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe
```

Later in the same comment I found the "real" file in another location:

> If I try to locate the "real" (?) msrdc.exe, I find it here: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe, which is not the same directory as the one referenced in the logs.

That is the file that is 2.5Mb:

> ```
> $ ls -alh /mnt/c/Program\ Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe/msrdc.exe
> -r-xr-xr-x 1 hag hag 2.5M Dec 18 03:30 '/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe/msrdc.exe'
> ```

So it looks like WSL is trying to use a corrupted version of `msrdc.exe` in my case.

Here is the output of `ls /proc/sys/fs/binfmt_misc` as requested:

`systemd=true`:

```
$ ls -al /proc/sys/fs/binfmt_misc
total 0
drwxr-xr-x 2 root root 0 Dec 22 16:45 .
dr-xr-xr-x 1 root root 0 Dec 22 16:45 ..
-rw-r--r-- 1 root root 0 Dec 22 16:45 jar
-rw-r--r-- 1 root root 0 Dec 22 16:45 jarwrapper
-rw-r--r-- 1 root root 0 Dec 22 16:45 llvm-11-runtime.binfmt
-rw-r--r-- 1 root root 0 Dec 22 16:45 llvm-13-runtime.binfmt
-rw-r--r-- 1 root root 0 Dec 22 16:45 llvm-14-runtime.binfmt
-rw-r--r-- 1 root root 0 Dec 22 16:45 llvm-9-runtime.binfmt
-rw-r--r-- 1 root root 0 Dec 22 16:45 python2.7
-rw-r--r-- 1 root root 0 Dec 22 16:45 python3.10
-rw-r--r-- 1 root root 0 Dec 22 16:45 python3.11
--w------- 1 root root 0 Dec 22 16:45 register
-rw-r--r-- 1 root root 0 Dec 22 16:45 status
```

`systemd=false`:

```
$ ls -al /proc/sys/fs/binfmt_misc
total 0
drwxr-xr-x 2 root root 0 Dec 20 19:30 .
dr-xr-xr-x 1 root root 0 Dec 20 19:30 ..
-rw-r--r-- 1 root root 0 Dec 20 19:30 qemu-aarch64
-rw-r--r-- 1 root root 0 Dec 20 19:30 qemu-arm
-rw-r--r-- 1 root root 0 Dec 20 19:30 qemu-mips64
-rw-r--r-- 1 root root 0 Dec 20 19:30 qemu-mips64el
-rw-r--r-- 1 root root 0 Dec 20 19:30 qemu-ppc64le
-rw-r--r-- 1 root root 0 Dec 20 19:30 qemu-riscv64
-rw-r--r-- 1 root root 0 Dec 20 19:30 qemu-s390x
--w------- 1 root root 0 Dec 20 19:30 register
-rw-r--r-- 1 root root 0 Dec 20 19:30 status
-rw-r--r-- 1 root root 0 Dec 20 19:30 WSLInterop

$ cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags: PF
offset 0
magic 4d5a
```

**Comment by OfekShilon** [comment]
@OneBlue @hideyukn88  got any directions? Any more info might help?

**Comment by hideyukn88** [comment]
@hagronnestad, would you please double check WSLInterop is missing when systemd is enabled? thanks!

**Comment by hagronnestad** [comment]
@hideyukn88 Confirmed.

```
$ cat /etc/wsl.conf
[boot]
systemd=true

$ cat /proc/sys/fs/binfmt_misc/WSLInterop
cat: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
```

```
$ cat /etc/wsl.conf
[boot]
#systemd=true

$ cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags: PF
offset 0
magic 4d5a
```

**Comment by OfekShilon** [comment]
@hideyukn88  @hagronnestad  So is the root cause isolated? Can we expect a fix?

**Comment by OfekShilon** [comment]
This has been open for 3 months now. Any word on the status?

**Comment by OfekShilon** [comment]
Not sure if this was fixed deliberately or not, but it seems solved for me.
Updated wsl version info:
```
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1325
```

Closing the issue, thanks.

**Comment by D3vil0p3r** [comment]
I guess to have your same past issue despite I'm using the latest version of WSL2 in Windows 11: https://github.com/microsoft/wslg/issues/1132https://github.com/microsoft/wslg/issues/1132 How did you fix that issue?

**Comment by konetsu** [comment]
not exactly the same issue since my main goal was using the rdp. but should be related and you can fix the problem even if ur not using rdp.

i was having the same problem. with systemd enabled, the gui wouldn't load. just blank black screen on rdp window. 
adding these lines fixed it for me:
unset DBUS_SESSION_BUS_ADDRESS
unset XDG_RUNTIME_DIR
dbus-launch

the whole startwm.sh looks like this. 
```
#!/bin/sh
# xrdp X session start script (c) 2015, 2017, 2021 mirabilos
# published under The MirOS Licence

# Rely on /etc/pam.d/xrdp-sesman using pam_env to load both
# /etc/environment and /etc/default/locale to initialise the
# locale and the user environment properly.

if test -r /etc/profile; then
        . /etc/profile
fi

if test -r ~/.profile; then
        . ~/.profile
fi

#test -x /etc/X11/Xsession && exec /etc/X11/Xsession
#exec /bin/sh /etc/X11/Xsession

unset DBUS_SESSION_BUS_ADDRESS
unset XDG_RUNTIME_DIR
dbus-launch

startxfce4
```

**Comment by daedsidog** [comment]
I am currently having this problem on the latest version.

```
WSL version: 2.1.4.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.4046
```

Is there a solution other than disabling systemd?

**Comment by dhtzs** [comment]
@daedsidog I'm experiencing the same problem.
