### ISSUE TITLE
gnome-language-selector didn't work

### ISSUE THREAD

**Issue by huhaorui** [microsoft/wslg#99]
# Environment

```none
Windows build number: 10.0.21364.1000
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.17.1
```

# Steps to reproduce

Open Language Spport in Windows start menu or use "gnome-language-selector" in terminal, it don't work. 
![image](https://user-images.githubusercontent.com/43870434/115995234-08f52000-a60d-11eb-8142-48b6ba2977a2.png)
(The Chinese character in the picture means "No such file or dictionary")

#  Expected behavior

it should open a window of language selector.

# Actual behavior

It didn't work.

**Comment by hideyukn88** [comment]
@huhaorui , thanks for reporting! This is because current Ubuntu distro for WSL is not configured for desktop usage by default, thus certain things have to be done manually, especially in your case, starting up dbus. Please try...

0: (assuming everything is properly installed)
1: sudo systemctl enable dbus
2: sudo /etc/init.d/dbus start

Then I'm able to run. WSLg can't do this automatically since these steps can be vary by distro. Thanks!

![image](https://user-images.githubusercontent.com/13857962/116102482-99f6e600-a663-11eb-82d3-bfdb3c4526ae.png)

**Comment by huhaorui** [comment]
Thank you! It works.



---Original---
From: "Hideyuki ***@***.***&gt;
Date: Mon, Apr 26, 2021 22:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/wslg] gnome-language-selector didn't work (#99)




 
@huhaorui , thanks for reporting! This is because current Ubuntu distro for WSL is not configured for desktop usage by default, thus certain things have to be done manually, especially in your case, starting up dbus. Please try...
 
0: (assuming everything is properly installed)
 1: sudo systemctl enable dbus
 2: sudo /etc/init.d/dbus start
 
Then I'm able to run. WSLg can't do this automatically since these steps can be vary by distro. Thanks!
